### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by Reality64** [dev6920/discord-mass-report-bot#1]
it keeps on saying "Error"

**Comment by dev6920** [comment]
- Python 3.8 or above is required.
- I develop for Windows machines only and do not intentionally support other operating systems.
- If the bot doesn't work then open command panel and type pip install colorama


1. Run main.py.
2. Paste the Discord Token
3. Discord server's ID the message was posted in.
4. Paste the channel ID.
5. Paste the message ID.
6. Select a reasonable reason to the report.
7. All set!
